config/routes.rb
Rails.application.routes.draw do
  resources :picture_albums
  devise_for :users
  get 'home/index'
  
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture_album.rb
class PictureAlbum < ApplicationRecord
	belongs_to :user
	
end

app/models/user.rb
class User < ApplicationRecord			
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :picture_album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/picture_albums_controller.rb
class PictureAlbumsController < ApplicationController
  before_action :set_picture_album, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /picture_albums
  # GET /picture_albums.json
  def index
    @picture_albums = current_user.picture_album
  end

  # GET /picture_albums/1
  # GET /picture_albums/1.json
  def show
  end

  # GET /picture_albums/new
  def new
    @picture_album = PictureAlbum.new
  end

  # GET /picture_albums/1/edit
  def edit
  end

  # POST /picture_albums
  # POST /picture_albums.json
  def create
    @picture_album = PictureAlbum.new(picture_album_params)

    respond_to do |format|
      if @picture_album.save
        format.html { redirect_to @picture_album, notice: 'Picture album was successfully created.' }
        format.json { render :show, status: :created, location: @picture_album }
      else
        format.html { render :new }
        format.json { render json: @picture_album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /picture_albums/1
  # PATCH/PUT /picture_albums/1.json
  def update
    respond_to do |format|
      if @picture_album.update(picture_album_params)
        format.html { redirect_to @picture_album, notice: 'Picture album was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture_album }
      else
        format.html { render :edit }
        format.json { render json: @picture_album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /picture_albums/1
  # DELETE /picture_albums/1.json
  def destroy
    @picture_album.destroy
    respond_to do |format|
      format.html { redirect_to picture_albums_url, notice: 'Picture album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture_album
      @picture_album = PictureAlbum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_album_params
      params.require(:picture_album).permit(:title, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/picture_albums_helper.rb
module PictureAlbumsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header.html.erb
<!--_header.htmal.erb-->
<% if user_signed_in? %>
   <%= current_user.email %>
   <%= link_to 'sign out' , destroy_user_session_path, method: :delete %>
<% else %>
   <%= link_to 'add album', new_picture_album_path %>
   <%= link_to 'sign in' , new_user_session_path %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Album</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</body>
</html>

app/views/picture_albums/_form.html.erb
<%= form_with(model: picture_album, local: true) do |form| %>
  <% if picture_album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture_album.errors.count, "error") %> prohibited this picture_album from being saved:</h2>

      <ul>
      <% picture_album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/picture_albums/edit.html.erb
<h1>Editing Picture Album</h1>

<%= render 'form', picture_album: @picture_album %>

<%= link_to 'Show', @picture_album %> |
<%= link_to 'Back', picture_albums_path %>

app/views/picture_albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Picture Albums</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @picture_albums.each do |picture_album| %>
      <tr>
        <td><%= picture_album.title %></td>
        <td><%= picture_album.description %></td>
        <td><%= link_to 'Show', picture_album %></td>
        <td><%= link_to 'Edit', edit_picture_album_path(picture_album) %></td>
        <td><%= link_to 'Destroy', picture_album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture Album', new_picture_album_path %>

app/views/picture_albums/new.html.erb
<h1>New Picture Album</h1>

<%= render 'form', picture_album: @picture_album %>

<%= link_to 'Back', picture_albums_path %>

app/views/picture_albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @picture_album.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture_album.description %>
</p>

<%= link_to 'Edit', edit_picture_album_path(@picture_album) %> |
<%= link_to 'Back', picture_albums_path %>